version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
      - sam --version
  pre_build:
    commands:
      - echo "Installing dependencies"
      - sam build
  build:
    commands:
      - echo "Deploying SAM application"
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name lambda-piped --s3-bucket lambda-piped --capabilities CAPABILITY_IAM
