version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
      - sam --version
  pre_build:
    commands:
      - echo "Installing dependencies"
      - sam build
  build:
    commands:
      - echo "Deploying SAM application"
      - sam deploy --stack-name lambda-piped
